Fix iptables rules loading!

diff --git a/firevigeo-prepare b/firevigeo-prepare
--- a/firevigeo-prepare
+++ b/firevigeo-prepare
@@ -1,7 +1,84 @@
 #!/usr/bin/env bash
 
-verbose_mode="false"
+###################################################################################
+#                                                                                 #
+# firevigeo                                                                       #
+#                                                                                 #
+# version: 0.6.2                                                                  #
+#                                                                                 #
+# A tool to start multiple tor proxys with transparent loadbalancing feature!     #
+# This tool redirect the complete traffic trough loadbalanced tor clients, with   #
+#  - extra custom tor configs                                                     #
+#  - an optionally conky Tor Network infobar!                                     #
+#  - globaly transparent loadbalanced tor network subsystem!                      #
+#  - seperate virtual dummy network cards for each tor client!                    #
+#  - generate a random control-port password for each tor client!                 #
+#  - and many more!                                                               #
+#                                                                                 #
+#  ________________________________________________________________________       #
+#                                                                                 #
+#   This tool require go-dispatch-proxy and redsocks proxy to work correct!       #
+#                                                                                 #
+#   __________________________________________________________________            #
+#                                                                                 #
+#                   Copyright (C) 2021-2022 Nonie689                              #
+#                                                                                 #
+#   Website: https://github.com/Nonie689/firevigeo-torloader                      #
+#                                                                                 #
+#                                                                                 #
+# _____________________________________________________________________________   #
+#   --- GNU GENERAL PUBLIC LICENSE ---                                            #
+#                                                                                 #
+#    This program is free software: you can redistribute it and/or modify         #
+#    it under the terms of the GNU General Public License as published by         #
+#    the Free Software Foundation, either version 3 of the License, or            #
+#    (at your option) any later version.                                          #
+#                                                                                 #
+#    This program is distributed in the hope that it will be useful,              #
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of               #
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
+#    GNU General Public License for more details.                                 #
+#                                                                                 #
+#    You should have received a copy of the GNU General Public License            #
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.        #
+#                                                                                 #
+###################################################################################
 
+
+## General
+#
+# program information
+readonly prog_name="firevigeo"
+readonly version="0.6.2"
+readonly signature="Copyright (C) 2022 Nonie689"
+readonly git_url="https://github.com/Nonie689/firevigeo-torloader"
+
+# set colors for stdout
+export red="$(tput setaf 1)"
+export green="$(tput setaf 2)"
+export yellow="$(tput setaf 3)"
+export blue="$(tput setaf 4)"
+export magenta="$(tput setaf 5)"
+export cyan="$(tput setaf 6)"
+export white="$(tput setaf 7)"
+export b="$(tput bold)"
+export reset="$(tput sgr0)"
+
+
+
+
+
+## Display program version
+print_version() {
+    printf "%s\\n" "${prog_name} ${version}"
+    printf "%s\\n" "${signature}"
+    printf "%s\\n" "License GPLv3: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>"
+    printf "%s\\n" "This is free software: you are free to change and redistribute it."
+    printf "%s\\n\n" "There is NO WARRANTY, to the extent permitted by law."
+}
+
+
+verbose_mode="false"
 
 check_root() {
     if [[ "${UID}" -ne 0 ]]; then
@@ -10,37 +87,49 @@ check_root() {
     fi
 }
 
-
 __init__ () {
 
-paramerr=false
+param_error=false
 
+# Show programm info!
+print_version
+
+
+# Check depencies
 not_there=false
-if ! which tor > /dev/null 2>&1 ; then
+if ! which tor &> /dev/null ; then
   echo "Found not tor! - Please install it!"
   not_there=true
 fi
 
-if ! which go-dispatch-proxy > /dev/null 2>&1 ; then
+if ! which go-dispatch-proxy &> /dev/null ; then
   echo "Found not go-dispatch-proxy! - Please install it!"
   not_there=true
 else
   setcap cap_net_raw=eip $(which go-dispatch-proxy)
 fi
 
-if ! which redsocks > /dev/null 2>&1 ; then
+if ! which redsocks &> /dev/null ; then
   echo "Found not redsocks! - Please install it!"
   not_there=true
 fi
 
-if ! which conky > /dev/null 2>&1 ; then
+if ! which conky &> /dev/null ; then
   echo "Found not conky - Please install it!"
+  not_there=true
+fi
+
+if ! which proxychains &> /dev/null ; then
+  echo "Found not proxychains - Please install it!"
   not_there=true
 fi
 
 if $not_there ; then
 exit 2
 fi
+
+sleep 1
+
 }
 
 generate_random(){
@@ -52,11 +141,11 @@ function __main__() {
   check_root
   
   # Killall runnig tor processes if existing!
-  kill $(pidof tor) &> /dev/null
+  killall tor &> /dev/null || kill $(pidof tor) &> /dev/null
   __init__
 
   own_params "${@}"
-  modprobe dummy
+  modprobe dummy &> /dev/null
 
 }
 
@@ -75,6 +164,7 @@ start_tor_servers() {
   readonly script="$0"
   readonly basename="$(dirname $script)"
 
+  echo "Change DNS service to use Tor DNS service!"
   echo "nameserver 127.0.0.1" > /etc/resolv.conf
 
   #  Early inititialisation part -  Setting up start variables with needet init values!
@@ -99,28 +189,37 @@ start_tor_servers() {
   dnsport=53
   ip_addr=10
 
-  # Saved new hashed pass as readable file
- echo "Saved new hashed pass to /etc/tor/hashed_pass" &&  echo -e "
-   ###############################################################
- \n####### Passwords for all tor  processed started with firevigeo!\n#######Generated on:  $_init_date   for  Tor Proxy Number from    $start till $end ! \n####### Number of Tor Proxy clients =   $number_torsrv_wanted!\n###############################################################\n\n\n# Readable Tor password\n_pass_plain=$_tor_pass_readable\n\n# Generated hash Tor password\n_pass_hash=$_tor_hashpass" > /etc/tor/hashed_pass && chmod 600  /etc/tor/hashed_pass
+  # Saved new hashed pass as readable file at: /etc/tor/hashed_pass
+  echo "Saved new Tor Control password store file at: /etc/tor/hashed_pass" && echo &&  echo -e "
+  ###############################################################
+ \n####### Passwords for all tor  processed started with firevigeo! #######\n#######Generated on:  $_init_date   for  Tor Proxy Number from    $start till $end ! ###########\n####### Number of Tor Proxy clients =   $number_torsrv_wanted!##########\n###############################################################\n\n\n# Readable Tor password\n_pass_plain=$_tor_pass_readable\n\n# Generated hash Tor password\n_pass_hash=$_tor_hashpass" > /etc/tor/hashed_pass && chmod 600  /etc/tor/hashed_pass
 
-   # Copy uncomplete conky config to  systemfolder!    ----    Using  files from script  ."/data/config"  folder 
-   mkdir -p "/etc/conky/cpu-colors-edit/" 2> /dev/null
+   # Copy uncomplete conky config to  systemfolder!    ----    Using  files from script  ."/data/config"  folder
+   if ! test -d /etc/conky/cpu-colors-edit/ ; then
+     echo "Create system settings folder for conkyrc file!" 
+     mkdir -p "/etc/conky/cpu-colors-edit/" 2> /dev/null
+   fi
+
+   # Generate custom conky and proxychain setting section!
+   echo "Generate custom conky and proxychains settings!" 
    cp -f "${basename}/data/config/conkyrc" "/etc/conky/cpu-colors-edit/.conkyrc"
 
+
+   # Generate for each Tor client custom settings and start the Tor Proxy clients!
+   echo -e "\nGenerate for each Tor client custom settings and start the Tor Proxy clients!"
 
    ### Run  forloop and create custom configs for conky and proxychain!
    for number in $(seq $start $end)
     do
 	newcontrolport="$(expr $number + 1100)"
-    echo "Tor socks: $number "
+    printf "Generate Tor socks: $number "
 
     # Create  proxychain config foreach tor proxy device with new settings !
-    cp "${basename}/data/config/proxychains.conf" $_proxychain_config.$counter.conf
-    echo "socks4 10.0.0.$ip_addr $number" >> $_proxychain_config.$counter.conf
-	
-   # Add  custom conkycode to conkyrc  tor displaying tor proxy stuff!
-    echo \${goto 12}\${voffset 0}\${font Ubuntu:style=Bold:size=8}Tor $counter_rw IP: \${alignr}\${color2}\${execp proxychains -q -f $_proxychain_config.$counter.conf 'curl -s https://myip.privex.io/index.json| jq  -r .ip' }\${color} >> /etc/conky/cpu-colors-edit/.conkyrc
+    cp "${basename}/data/config/proxychains.conf" $_proxychain_config.$counter_rw.conf
+    echo "socks4 10.0.0.$ip_addr $number" >> $_proxychain_config.$counter_rw.conf
+
+    # Add  custom conkycode to conkyrc  tor displaying tor proxy stuff!
+    echo \${goto 12}\${voffset 0}\${font Ubuntu:style=Bold:size=8}Tor $counter_rw IP: \${alignr}\${color2}\${execp proxychains -q -f $_proxychain_config.$counter_rw.conf 'curl -s https://myip.privex.io/index.json| jq  -r .ip' }\${color} >> /etc/conky/cpu-colors-edit/.conkyrc
   
     # Set torrc config
     # Add foreach Tor-Gateway device extra torrc options with new custom settings!!
@@ -128,6 +227,10 @@ start_tor_servers() {
     echo "ExitNodes {eg},{hk},{ph},{tj},{tw},{th},{kp},{jp},{ru} StrictNodes 1" >> $_torrc_config.$number
     echo "User tor" >> $_torrc_config.$number
     echo "Sandbox 1" >> $_torrc_config.$number
+    echo "HardwareAccel 1" >> $_torrc_config.$number
+    echo "BandwidthBurst 1547483647" >> $_torrc_config.$number
+    echo "BandwidthRate 1547483647" >> $_torrc_config.$number
+    #echo "ConnLimit $(ulimit -H -n)" >> $_torrc_config.$number
     echo "NewCircuitPeriod 7" >> $_torrc_config.$number
     cp -rp "/var/lib/tor" "/var/lib/tor.$number"
     echo "DataDirectory /var/lib/tor.$number" >> $_torrc_config.$number
@@ -135,28 +238,32 @@ start_tor_servers() {
     ip_addr_list="$ip_addr_list 10.0.0.$ip_addr:$number"
     echo "ControlPort $newcontrolport" >> $_torrc_config.$number
     echo "HashedControlPassword $_tor_hashpass" >> $_torrc_config.$number
+
+    # Enable only at the first tor client a DNS service!
     if test $counter -eq 0 ; then
       echo "DNSPort $dnsport" >> $_torrc_config.$number
     fi
 
-    ip link add eth$counter type dummy  > /dev/null 2>&1 
-    ip addr add 10.0.0.$ip_addr/24 brd + dev eth$counter label eth$counter:0  > /dev/null 2>&1 
-    ip link set dev eth$counter up  > /dev/null 2>&1 
+    ip link add veth$counter type dummy  &> /dev/null 
+    ip addr add 10.0.0.$ip_addr/24 brd + dev veth$counter label veth$counter:0  &> /dev/null 
+    ip link set dev veth$counter up  &> /dev/null
 
     let counter=counter+1
     let counter_rw=counter_rw+1
     let ip_addr=ip_addr+1
 
-#Start tor proxy router for virtual  network card! Then check the  execution succeed!
-tor -f $_torrc_config.$number > /dev/null 2>&1 & 
-if [ $? -eq 0 ] ; then
-      echo "Tor $counter started!"
+    #Start tor proxy router for virtual  network card! Then check the  execution succeed!
+    tor -f $_torrc_config.$number &> /dev/null & 
+
+    if [ $? -eq 0 ] ; then
+      echo " -- Tor $counter started!"
     else
-      echo "Failed to start Tor!"
+      echo " -- Failed to start Tor!"
     fi
-	
-# End of loop for creating custom new settings!
+
+    # End of loop for creating custom new settings!
  done
+
 
    # Save conkyrc to users folder!
    UHOME="/home"
@@ -167,32 +274,65 @@ if [ $? -eq 0 ] ; then
      _dir="${UHOME}/${u}"
      if [ -d "$_dir" ]
      then
-	   mkdir -p $_dir/.conky/cpu-colors-edit 2> /dev/null 
-        cp -f /etc/conky/cpu-colors-edit/.conkyrc "$_dir/.conky/cpu-colors-edit/"
-         chown $(id -un $u):$(id -gn $u) "$_dir/.conky/cpu-colors-edit/.conkyrc"
+	 mkdir -p $_dir/.conky/cpu-colors-edit 2> /dev/null 
+         cmp --silent -- /etc/conky/cpu-colors-edit/.conkyrc "$_dir/.conky/cpu-colors-edit/.conkyrc" || cp -f /etc/conky/cpu-colors-edit/.conkyrc "$_dir/.conky/cpu-colors-edit/" && chown $(id -un $u):$(id -gn $u) "$_dir/.conky/cpu-colors-edit/.conkyrc"
      fi
   done
-     #Reset iptables
-     echo
-     echo "Reset iptables!"
-     /usr/bin/iptables -F && /usr/bin/iptables -t nat -F 
+
+  #Reset currently used iptables.rules
+  echo
+  echo "Unload currently used iptables.rules!"
+
+  while true ; do
+    if test `iptables --list | wc -l` -ne 8 ; then 
+      reset_iptables
+    else
+     break
+    fi
+  done
+     # Save iptables.rule, if not exist in system settings folder!
+     if test ! -f  /etc/iptables/redsocks-go-balanced.rules && ! test `cmp --silent "${basename}/data/config/redsocks.rules"  "/etc/iptables/redsocks-go-balanced.rules"` ; then echo "Save redsocks iptables rules!";cp -f "${basename}/data/config/redsocks.rules"  "/etc/iptables/redsocks-go-balanced.rules"; fi
      # Load iptables
-     echo "Load iptables!"
-     sleep 3
-     iptables-restore /etc/iptables/redsocks.rules 2> /dev/null
+     echo "Loading new custom iptables rules!"
+     cat /etc/iptables/redsocks-go-balanced.rules | iptables-restore  -c -w 2 &> /dev/null
      if [ "$?" -ne 0 ] ; then
-       echo "can't set /etc/iptables/iptables.rules"
+       echo "Error! - Failed to load new custom iptables rules!"
        exit 22
      fi
 
+     # Wait for real iptables load finish!
+     sleep 0.5
+
+     if test `iptables --list | grep -E "target     prot opt source               destination"| wc -l` -gt 14 ; then
+       echo "Iptables Loading done! -- System is now complete proxyfing traffic by loadbalancer!"
+     fi
+
+     pidof redsocks &> /dev/null || echo "Info -- Redsocks daemon is not running! Redsocks is required! Please don't forget to start this daemon after done this!" && echo
+     pidof go-dispatch-proxy &> /dev/null || echo "Info -- Go-dispatch-proxy is not running! Go-dispatch-proxy is required! Please don't forget to start this after done this!" && echo
+
+  echo "Finished custom systm configuration!"
+  echo
+  echo " -- Some additionaly infos for user --"
+  echo
   echo "Tor ControlPort readable password is: $_tor_pass_readable"
   echo "Tor ControlPort hashed password is: $_tor_hashpass"
   echo
-  echo "Start Load Balancer for: $ip_addr_list"
+  echo "Start Load Balancer with: go-dispatch-proxy -lport 4711 -tunnel $ip_addr_list"
 
   exit 0
 }
 
+
+reset_iptables() {
+     iptables -F
+     iptables -X
+     iptables -t nat -F
+     iptables -t nat -X
+     iptables -P INPUT ACCEPT
+     iptables -P FORWARD ACCEPT
+     iptables -P OUTPUT ACCEPT
+     sleep 0.5
+}
 
 own_params() {
     start=5090
@@ -263,11 +403,11 @@ own_params() {
     if [[ "$2" && "$3" ]]; then
 	if [[ $2 -le 1 || $2 -ge 65535 ]]; then
 	  echo "The allowed port range for the start port is 1-65535!"
-	  paramerr=true
+	  param_error=true
 	elif [[ $2 -le 1 || $2 -ge 65535 ]]; then
           echo "The allowed port range for the last port is 1-65535!"
-          paramerr=true
-	elif [[ ! $paramerr ]]; then
+          param_error=true
+	elif [[ ! $param_error ]]; then
 	  exit 2
 	fi
         if [[ "$#" -gt 1 ]]; then
